import { TableDataType } from '@/types/home';

export const ExampleData: TableDataType[] = [
  {
    Name: 'New Dashboard',
    Type: 'Boolean',
    Created: '2024-01-15',
    By: 'Alice',
    Status: false,
    'Default Value': false,
  },
  {
    Name: 'Feature Flags',
    Type: 'String',
    Created: '2024-02-01',
    By: 'KeunJae',
    Status: true,
    'Default Value': 'so',
  },
  {
    Name: 'Example 1',
    Type: 'Number',
    Created: '2024-01-28',
    By: 'Elon Musk',
    Status: true,
    'Default Value': 0,
  },
  {
    Name: 'Example 2',
    Type: 'String',
    Created: '2024-02-01',
    By: 'KeunJae',
    Status: true,
    'Default Value': 'so',
  },
  {
    Name: 'User Preferences',
    Type: 'Boolean',
    Created: '2024-03-05',
    By: 'Sarah',
    Status: false,
    'Default Value': true,
  },
  {
    Name: 'Application Mode',
    Type: 'String',
    Created: '2024-03-10',
    By: 'Michael',
    Status: true,
    'Default Value': 'production',
  },
  {
    Name: 'Retry Count',
    Type: 'Number',
    Created: '2024-03-15',
    By: 'Nina',
    Status: false,
    'Default Value': 3,
  },
  {
    Name: 'Notifications',
    Type: 'Boolean',
    Created: '2024-03-20',
    By: 'Tom',
    Status: true,
    'Default Value': true,
  },
  {
    Name: 'Dark Mode',
    Type: 'Boolean',
    Created: '2024-03-25',
    By: 'Emma',
    Status: false,
    'Default Value': false,
  },
  {
    Name: 'Max Items',
    Type: 'Number',
    Created: '2024-03-30',
    By: 'John',
    Status: true,
    'Default Value': 10,
  },
  {
    Name: 'User Role',
    Type: 'String',
    Created: '2024-04-05',
    By: 'Sophia',
    Status: true,
    'Default Value': 'user',
  },
  {
    Name: 'Enable Logging',
    Type: 'Boolean',
    Created: '2024-04-10',
    By: 'Alice',
    Status: false,
    'Default Value': true,
  },
  {
    Name: 'API Key',
    Type: 'String',
    Created: '2024-04-15',
    By: 'KeunJae',
    Status: true,
    'Default Value': '12345-abcde',
  },
  {
    Name: 'Connection Timeout',
    Type: 'Number',
    Created: '2024-04-20',
    By: 'Elon Musk',
    Status: false,
    'Default Value': 30,
  },
];
