import { FeatureFlagTableType, FeatureFlagType } from '@/types/types';

export const ExampleData: FeatureFlagTableType[] = [
  {
    Key: 'New Dashboard',
    type: FeatureFlagType.Boolean,
    createdAt: '2024-01-15',
    createdBy: 'Alice',
    status: false,
  },
  {
    Key: 'Feature Flags',
    type: FeatureFlagType.String,
    createdAt: '2024-02-01',
    createdBy: 'KeunJae',
    status: true,
  },
  {
    Key: 'Example 1',
    type: FeatureFlagType.Number,
    createdAt: '2024-01-28',
    createdBy: 'Elon Musk',
    status: true,
  },
  {
    Key: 'Example 2',
    type: FeatureFlagType.String,
    createdAt: '2024-02-01',
    createdBy: 'KeunJae',
    status: true,
  },
  {
    Key: 'User Preferences',
    type: FeatureFlagType.Boolean,
    createdAt: '2024-03-05',
    createdBy: 'Sarah',
    status: false,
  },
  {
    Key: 'Application Mode',
    type: FeatureFlagType.String,
    createdAt: '2024-03-10',
    createdBy: 'Michael',
    status: true,
  },
  {
    Key: 'Retry Count',
    type: FeatureFlagType.Number,
    createdAt: '2024-03-15',
    createdBy: 'Nina',
    status: false,
  },
  {
    Key: 'Notifications',
    type: FeatureFlagType.Boolean,
    createdAt: '2024-03-20',
    createdBy: 'Tom',
    status: true,
  },
  {
    Key: 'Dark Mode',
    type: FeatureFlagType.Boolean,
    createdAt: '2024-03-25',
    createdBy: 'Emma',
    status: false,
  },
  {
    Key: 'Max Items',
    type: FeatureFlagType.Number,
    createdAt: '2024-03-30',
    createdBy: 'John',
    status: true,
  },
  {
    Key: 'User Role',
    type: FeatureFlagType.String,
    createdAt: '2024-04-05',
    createdBy: 'Sophia',
    status: true,
  },
  {
    Key: 'Enable Logging',
    type: FeatureFlagType.Boolean,
    createdAt: '2024-04-10',
    createdBy: 'Alice',
    status: false,
  },
  {
    Key: 'API Key',
    type: FeatureFlagType.String,
    createdAt: '2024-04-15',
    createdBy: 'KeunJae',
    status: true,
  },
  {
    Key: 'Connection Timeout',
    type: FeatureFlagType.Number,
    createdAt: '2024-04-20',
    createdBy: 'Elon Musk',
    status: false,
  },
];
