import { featureFlagTableType } from '@/types/types';

export const ExampleData: featureFlagTableType[] = [
  {
    Key: 'New Dashboard',
    Type: 'Boolean',
    Created: '2024-01-15',
    By: 'Alice',
    ToggleButton: false,
  },
  {
    Key: 'Feature Flags',
    Type: 'String',
    Created: '2024-02-01',
    By: 'KeunJae',
    ToggleButton: true,
  },
  {
    Key: 'Example 1',
    Type: 'Number',
    Created: '2024-01-28',
    By: 'Elon Musk',
    ToggleButton: true,
  },
  {
    Key: 'Example 2',
    Type: 'String',
    Created: '2024-02-01',
    By: 'KeunJae',
    ToggleButton: true,
  },
  {
    Key: 'User Preferences',
    Type: 'Boolean',
    Created: '2024-03-05',
    By: 'Sarah',
    ToggleButton: false,
  },
  {
    Key: 'Application Mode',
    Type: 'String',
    Created: '2024-03-10',
    By: 'Michael',
    ToggleButton: true,
  },
  {
    Key: 'Retry Count',
    Type: 'Number',
    Created: '2024-03-15',
    By: 'Nina',
    ToggleButton: false,
  },
  {
    Key: 'Notifications',
    Type: 'Boolean',
    Created: '2024-03-20',
    By: 'Tom',
    ToggleButton: true,
  },
  {
    Key: 'Dark Mode',
    Type: 'Boolean',
    Created: '2024-03-25',
    By: 'Emma',
    ToggleButton: false,
  },
  {
    Key: 'Max Items',
    Type: 'Number',
    Created: '2024-03-30',
    By: 'John',
    ToggleButton: true,
  },
  {
    Key: 'User Role',
    Type: 'String',
    Created: '2024-04-05',
    By: 'Sophia',
    ToggleButton: true,
  },
  {
    Key: 'Enable Logging',
    Type: 'Boolean',
    Created: '2024-04-10',
    By: 'Alice',
    ToggleButton: false,
  },
  {
    Key: 'API Key',
    Type: 'String',
    Created: '2024-04-15',
    By: 'KeunJae',
    ToggleButton: true,
  },
  {
    Key: 'Connection Timeout',
    Type: 'Number',
    Created: '2024-04-20',
    By: 'Elon Musk',
    ToggleButton: false,
  },
];
