spring:
    application:
        name: LightSwitch
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: create
        open-in-view: false
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:lightswitch.sqlite

jwt:
    secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
