spring:
  application:
    name: LightSwitch
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    url: jdbc:sqlite:lightswitch.sqlite
    driver-class-name: org.sqlite.JDBC

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
